#pragma once
#define SC_PLAYER_LEFT_UP 17
#define SC_PLAYER_LEFT_DOWN 18
#define SC_PLAYER_RIGHT_UP 19
#define SC_PLAYER_RIGHT_DOWN 20
#define TYPE_PLAYER		0
#define TYPE_BULLET		1

#define DIR_LEFT_GO 101
#define DIR_LEFT_STOP 102
#define DIR_RIGHT_GO 103
#define DIR_RIGHT_STOP 104